services:
  redis:
    image: redis:8.4.2-alpine
    container_name: redis
    restart: unless-stopped
    platform: linux/arm64/v8        # 解决 Mac M 系列架构警告
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis/redis-data:/data          # Mac 可挂载、不报错
    command: >
      redis-server
      --requirepass "Pass@1234"
      --appendonly yes
      --maxmemory 1600mb
    mem_limit: 2g
    cpus: 2

