
services:
  pgvector:
    image: pgvector/pgvector:pg17  # 内置PG16 + pgvector 0.8.2
    platform: linux/amd64
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: Pass@1234
      POSTGRES_DB: rag_db
      PGDATA: /var/lib/postgresql/data/pgdata  # 数据目录
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgsql -d rag_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: